language: csharp
mono: none
dotnet: 2.2.100
solution: solution-name.sln
install:
  - dotnet restore
script:
  - dotnet build -c Release Postal.sln
  - cd ./src/Postal.Tests/
  - dotnet test -c Release